"""Temporary CP2 guard: the container restructure must not change one pixel.

Baselines are generated by running this file BEFORE the restructure (first run
writes them) and compared after. Deleted in CP3, when the UI changes on purpose.
"""

import re
from datetime import UTC, datetime
from pathlib import Path

import pytest

from oflow.core.config import TabConfig
from oflow.integrations.linear.source import Issue
from oflow.shell.app import OflowApp
from oflow.shell.panel import PanelState

FIXTURES = Path(__file__).parent / "fixtures"
NOW = datetime(2026, 8, 13, 12, 0, tzinfo=UTC)

ISSUES = tuple(
    Issue(
        id=f"ENG-{index}",
        updated_at=NOW,
        url=f"https://linear.app/x/issue/ENG-{index}",
        title=f"title of ENG-{index}",
        status="In Review" if index == 1 else "Todo",
        status_type="started",
        team="Infra",
        priority="High",
    )
    for index in (1, 2, 3)
)


def fake_ready(self, integration_id, panel, force=False):
    panel.items = ISSUES
    panel.state = PanelState.READY


def fake_error(self, integration_id, panel, force=False):
    panel.state = PanelState.ERROR
    panel.message = "Linear is unreachable"


@pytest.mark.parametrize("fake", [fake_ready, fake_error], ids=["ready", "error"])
@pytest.mark.asyncio
async def test_screen_matches_baseline(fake, monkeypatch, request):
    monkeypatch.setattr("oflow.shell.app.OflowApp.refresh_tab", fake)
    app = OflowApp(tabs=(TabConfig("linear"),))
    async with app.run_test() as pilot:
        await pilot.pause()
        svg = app.export_screenshot()

    baseline = FIXTURES / f"cp2_{request.node.callspec.id}.svg"
    if not baseline.exists():
        baseline.write_text(svg)
        pytest.skip("baseline written; rerun to compare")
    # Rich's SVG unique_id is a checksum of the raw segment stream, not the
    # rendered glyphs: a widget-tree restructure can shift that stream (e.g. an
    # inherited vs. explicit Style attribute) with zero visible effect, which
    # changes the id though nothing about what is actually painted moved.
    normalize = lambda text: re.sub(r"terminal-\d+", "terminal", text)  # noqa: E731
    assert normalize(svg) == normalize(baseline.read_text())
